<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Balzor.Chat.Components/Balzor.Chat.Components.csproj" />
    <ProjectReference Include="..\DemoAIDynamicSession.ServiceDefaults\DemoAIDynamicSession.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
